### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by cvburgess** [jmeas/moment-business#12]
When I do `today.workDays( tomorrow )` where today and tomorrow are moments a day apart, I get `Undefined is not a function` - is there something I am doing wrong?

`.addWorkDays()` and `.subtractWorkDays()` are working fine

**Comment by jamesplease** [comment]
Can you give me more info? A failing test case or something?

What browser are you using?

**Comment by jamesplease** [comment]
Here are [the tests](https://github.com/jmeas/moment-business/blob/master/test/unit/week-days.js) if that helps you debug the problemo.

**Comment by jamesplease** [comment]
@cvburgess, did you figure this out? Is it a problem w. this library? :open_mouth:

**Comment by jamesplease** [comment]
oh, loool. The fn name is [`weekDays`](https://github.com/jmeas/moment-business/blob/master/src/moment-business.js#L4), not `workDays`. The docs are wrong. Will-fix.

**Comment by jamesplease** [comment]
I updated the docs to reflect the _correct_ method name. Then went ahead and changed all of the names to be more consistent about whether they're 'work days' or 'week days' (it's always week days, now)
