### ISSUE TITLE
How do i use it?

### ISSUE THREAD

**Issue by AScripnic** [jmeas/moment-business#28]
var final = moment(date).weekDays(date2); if like this it isn't working

**Comment by jamesplease** [comment]
From [the documentation](https://github.com/jmeas/moment-business#weekdays-othermoment-), `date2` must be a moment. Also, there are unit tests that show [its usage](https://github.com/jmeas/moment-business/blob/master/test/unit/week-days.js#L15).

If this still doesn't help ya, let me know. Closing for now.
