### ISSUE TITLE
off-by-one error on weekDays (maybe due to moment#diff)

### ISSUE THREAD

**Issue by leobalter** [jmeas/moment-business#32]
Seems like there is a problem at [`moment#diff`](http://momentjs.com/docs/#/displaying/difference/), used by the `weekDays` method.

You can reproduce the same bug on moment-business with these tests: https://github.com/jmeas/moment-business/compare/jmeas:master...leobalter:return-proper-weekdays?expand=1 

I didn't open a PR with these tests as they're not following the standard from the other tests, we could improve it.

I checked the return from the [.diff call at weekDays](https://github.com/jmeas/moment-business/blob/master/src/moment-business.js#L6) and the off-by-one is happening there.

**Comment by leobalter** [comment]
I'm making a huge mistake here. 

weekdays returns 0 if `this` and `otherMoment` are in the same day, right? If yes, this issue is wrong and we can close it.

**Comment by jamesplease** [comment]
Thanks for the issue, @leobalter !

However, it's looking like this isn't an issue with `moment-business`. Rather, you're assuming that this algorithm has an inclusive start and inclusive end.

`moment-business`, `moment` and most good date libraries will have inclusive starts and exclusive end algorithms, and [for good reason!](http://qedcode.com/content/exclusive-end-dates).

I **strongly** encourage you to make sure that you're conscious of whether the dates you're working with are inclusive or exclusive, and to verify that the algorithms that you consume and write match up with those dates! It can be super tough, for sure, but it's a necessary thing to be aware of to create working algorithms.

I'll leave a Bocoup-specific note in the Away issue :)

Gonna close for now.

**Comment by jamesplease** [comment]
Spoke more with @leobalter and we found a good test case:

``` js
start = moment.utc('2015-11-02', DATE_FORMAT);
endMoment = moment.utc('2015-11-05', DATE_FORMAT);
weekDays = start.weekDays(endMoment);
```

Should be 3, but it's coming out as 2.

**Comment by jamesplease** [comment]
Research for myself:

It's calculating that there's somehow a Saturday between those two dates. The offending line is:

`var containedSaturdays = containedPeriodicValues(startDay, totalDays + startDay, 6, 7);`

The signature of `containedPeriodicValues` is `(start, end, value, period)`. I'm passing in:

`4, 7, 6, 7`

It looks as if I may be mixing up the start and end values for `containedPeriodicValues`.

**Comment by jamesplease** [comment]
Pretty sure this issue is because this algorithm isn't symmetric about the y-axis, and I'm assuming it to be. Will investigate more soon

**Comment by jamesplease** [comment]
I'm working on a vanilla JS version of this lib; I'll be fixing this over there. I'll let you know. Once that's done, eventually Admiralty should be updated. //cc @tkellen

**Comment by jamesplease** [comment]
This seems to be an issue with ordering. Here's the example we were using that produced the wrong answer:

``` js
start = moment.utc('2015-11-02', DATE_FORMAT);
endMoment = moment.utc('2015-11-05', DATE_FORMAT);
weekDays = start.weekDays(endMoment);
```

if you switch `start` and `endMoment`, then the result is correct. I think the resolution of this is two things:
1. correctly handling the order being switched (moment returns a negative value) 
2. documenting this better

So the tl;dr is that the argument order to get positive values is:

`end.weekDays(start);`

**Comment by jamesplease** [comment]
@leobalter this has been fixed as of the latest release. Rather than giving 2, your example will now return -3 (since the order is swapped).

@tkellen there's nothing to worry about in Admiralty. Since the order of the args was right in Admiralty the last time I saw that code, it should be good :v:

**Comment by tkellen** [comment]
thanks @jmeas!
