### ISSUE TITLE
Clarify documentation for weekDays / weekendDays

### ISSUE THREAD

**Issue by kjr** [jmeas/moment-business#33]
Please can you make the documentation in the README clearer for using weekDays and weekendDays - please make it specific that these have to be used endMoment.weekDays(startMoment)

Just been using this with startMoment.weekDays(endMoment) and puzzling over weird responses - it was only when I looked at the source that I realised what was going on.

**Comment by jamesplease** [comment]
Good idea.

I almost think it's more important to point out that the signature of these follows the _exact same_ signature as every other Moment method, so those familiar with Moment should find this API pretty natural.

In any event, PRs are welcome!

**Comment by jamesplease** [comment]
Related: #32 which was caused by this

**Comment by jamesplease** [comment]
fixed! Thanks for the suggestion. Swapping the order behaves more predictably now; the result will just be negative.
