### ISSUE TITLE
How to use with TypeScript?

### ISSUE THREAD

**Issue by iwhp** [jmeas/moment-business#50]
I would like to use moment-business with TypeScript. Is there a d.ts available?
Thankx, Harry

**Comment by jamesplease** [comment]
There is not one available. I don't use TS, but i'd accept PR to add support.

**Comment by michaelstievenart** [comment]
Support in Typescript would be great!

**Comment by wonbyte** [comment]
+1

**Comment by wonbyte** [comment]
@iwhp you can just do 
```const buisness = require("moment-business");```
 in your .ts file for now.

**Comment by wonbyte** [comment]
@iwhp @jmeas I created the following PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15258 . Once it gets merged types should be available.

**Comment by wonbyte** [comment]
@iwhp @jmeas I've added the types to the definitely typed project. You should be set.  https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15271

**Comment by jamesplease** [comment]
@wonbyte , thank you **so** much! I definitely want folks to be able to use this with TypeScript, but I don't use it myself so it'd be tough for me to maintain that. I appreciate you taking the time to make the PR there.

I'm going to close this issue out. I'll also add a note to the README linking to that repo.

**Comment by wonbyte** [comment]
@jmeas Glad to help. Big thanks to you for moment-business. It's a fantastic library
